# Generated by Django 3.0.5 on 2020-04-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_auto_20150419_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='source',
            field=models.CharField(blank=True, choices=[('static', 'Static'), ('current', 'Current Location')], max_length=50, null=True),
        ),
    ]
