language: generic

services:
  - docker

jobs:
  include:
    - stage: install
      script: pip install virtualenv
    - stage: tests
      script: bash ./scripts/ci_tests.sh
    - stage: coverage
      script: pip install coveralls && coveralls
    - stage: deploy to staging
      script: skip
      deploy:
        provider: script
        script: bash scripts/deploy.sh $APP_NAME $STAGING_SMOKE_URL
        on:
          branch: master
    - stage: deploy to production
      script: skip
      deploy:
        provider: script
        script: bash scripts/deploy.sh $PRODUCTION_APP_NAME $PRODUCTION_SMOKE_URL
        on:
          branch: master