version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and Run Tests
          command: |
            bash ./scripts/ci_tests.sh
      - run:
          name: Build and push Docker image
          command: |
            echo "Publish docker image"