# Generated by Django 3.0.5 on 2020-04-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertdb', '0019_auto_20170923_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='cap_message_type',
            field=models.CharField(blank=True, choices=[('Alert', 'Alert'), ('Update', 'Update'), ('Cancel', 'Cancel'), ('Ack', 'Ack'), ('Error', 'Error')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='cap_scope',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Restricted', 'Restricted'), ('Private', 'Private')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='cap_status',
            field=models.CharField(blank=True, choices=[('Actual', 'Actual'), ('System', 'System'), ('Exercise', 'Exercise'), ('Test', 'Test'), ('Draft', 'Draft')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='area_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='geocode',
            name='value_name',
            field=models.CharField(blank=True, choices=[('FIPS6', 'FIPS6'), ('Taiwan_Geocode_100', 'Taiwan Townships'), ('SAME', 'SAME')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='cap_category',
            field=models.CharField(choices=[('Geo', 'Geo'), ('Met', 'Meteorological'), ('Safety', 'Safety'), ('Security', 'Security'), ('Rescue', 'Rescue'), ('Fire', 'Fire'), ('Health', 'Health'), ('Env', 'Env'), ('Transport', 'Transport'), ('Infra', 'Infrastructure'), ('CBRNE', 'CBRNE'), ('Other', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='info',
            name='cap_certainty',
            field=models.CharField(choices=[('Observed', 'Observed'), ('Likely', 'Likely'), ('Possible', 'Possible'), ('Unlikely', 'Unlikely'), ('Unknown', 'Unknown')], max_length=15),
        ),
        migrations.AlterField(
            model_name='info',
            name='cap_language',
            field=models.CharField(blank=True, default='', max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='cap_response_type',
            field=models.CharField(blank=True, choices=[('Shelter', 'Shelter'), ('Evacuate', 'Evacuate'), ('Prepare', 'Prepare'), ('Execute', 'Execute'), ('Avoid', 'Avoid'), ('Monitor', 'Monitor'), ('Assess', 'Assess'), ('AllClear', 'AllClear'), ('None', 'None')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='cap_severity',
            field=models.CharField(choices=[('Extreme', 'Extreme'), ('Severe', 'Severe'), ('Moderate', 'Moderate'), ('Minor', 'Minor'), ('Unknown', 'Unknown')], max_length=15),
        ),
        migrations.AlterField(
            model_name='info',
            name='cap_urgency',
            field=models.CharField(blank=True, choices=[('Immediate', 'Immediate'), ('Expected', 'Expected'), ('Future', 'Future'), ('Past', 'Past'), ('Unknown', 'Unknown')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
